---
title: "Preprocess your data with recipes" 
subtitle: "Tutorial from Tidymodels"
author: "Matheus Cardoso"
date: "Jun 23, 2020"
output: 
  html_document: 
    fig_caption: yes
    highlight: zenburn
    keep_md: yes
    theme: simplex
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, cache = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidymodels) # for the rsample package, along with the rest of tidymodels
library(tidyverse)
library(magrittr)

# Helper packages
library(modeldata) # for the cells data

```

```{r}
cells <- read_csv("./data/training.csv")
cells %<>% 
    drop_na() %>% 
    rename(class = classe) %>% 
    mutate(class = factor(class)) %>% 
    select(!X1) %>% 
    mutate(across(where(is.character), as.factor))
```

```{r}
set.seed(123)
cell_split <- initial_split(cells,
    strata = class
)

```

```{r}
cell_train <- training(cell_split)
cell_test <- testing(cell_split)

nrow(cell_train)
# > [1] 1515
nrow(cell_train) / nrow(cells)
# > [1] 0.7503715

# training set proportions by class
cell_train %>%
    count(class) %>%
    mutate(prop = n / sum(n))
# > # A tibble: 2 x 3
# >   class     n  prop
# >   <fct> <int> <dbl>
# > 1 PS      975 0.644
# > 2 WS      540 0.356

# test set proportions by class
cell_test %>%
    count(class) %>%
    mutate(prop = n / sum(n))
# > # A tibble: 2 x 3
# >   class     n  prop
# >   <fct> <int> <dbl>
# > 1 PS      325 0.645
# > 2 WS      179 0.355

```

```{r}
rf_mod <- 
  rand_forest(trees = 1000) %>%
      set_engine("ranger") %>%
  set_mode("classification")

```

```{r}
set.seed(234)
rf_fit <-
    rf_mod %>%
    fit(class ~ ., data = cell_train)
rf_fit

```

```{r}
rf_training_pred <- 
  predict(rf_fit, cell_train) %>%
      bind_cols(predict(rf_fit, cell_train, type = "prob")) %>%
      # Add the true outcome data back in
      bind_cols(cell_train %>%
                  select(class))
rf_training_pred %>%                # training set predictions
  roc_auc(truth = class, .pred_A, .pred_B, .pred_C, .pred_D, .pred_E)
  # > # A tibble: 1 x 3
  # >   .metric .estimator .estimate
  # >   <chr>   <chr>          <dbl>
  # > 1 roc_auc binary          1.00
rf_training_pred %>% # training set predictions
    accuracy(truth = class, .pred_class)
# > # A tibble: 1 x 3
# >   .metric  .estimator .estimate
# >   <chr>    <chr>          <dbl>
# > 1 accuracy binary         0.993

```

```{r}
rf_testing_pred <- 
    predict(rf_fit, cell_test) %>% 
    bind_cols(predict(rf_fit, cell_test, type = "prob")) %>% 
    bind_cols(cell_test %>% select(class))

rf_testing_pred %>%                   # test set predictions
  roc_auc(truth = class, .pred_A, .pred_B, .pred_C, .pred_D, .pred_E)
  # > # A tibble: 1 x 3
  # >   .metric .estimator .estimate
  # >   <chr>   <chr>          <dbl>
  # > 1 roc_auc binary         0.909
rf_testing_pred %>% 
    roc_curve(truth = class, .pred_A, .pred_B, .pred_C, .pred_D, .pred_E) %>% 
    autoplot()

rf_testing_pred %>% # test set predictions
    accuracy(truth = class, .pred_class)
# > # A tibble: 1 x 3
# >   .metric  .estimator .estimate
# >   <chr>    <chr>          <dbl>
# > 1 accuracy binary         0.837

```

```{r}
set.seed(345)
folds <- vfold_cv(cell_train, v = 100)
folds
# > #  10-fold cross-validation
# > # A tibble: 10 x 2
# >    splits             id
# >    <named list>       <chr>
# >  1 <split [1.4K/152]> Fold01
# >  2 <split [1.4K/152]> Fold02
# >  3 <split [1.4K/152]> Fold03
# >  4 <split [1.4K/152]> Fold04
# >  5 <split [1.4K/152]> Fold05
# >  6 <split [1.4K/151]> Fold06
# >  7 <split [1.4K/151]> Fold07
# >  8 <split [1.4K/151]> Fold08
# >  9 <split [1.4K/151]> Fold09
# > 10 <split [1.4K/151]> Fold10

```

```{r}
rf_wf <- 
  workflow() %>%
      add_model(rf_mod) %>%
      add_formula(class ~ .)

set.seed(456)
rf_fit_rs <-
    rf_wf %>%
    fit_resamples(folds)

# rf_fit_rs
# > #  10-fold cross-validation
# > # A tibble: 10 x 4
# >    splits             id     .metrics         .notes
# >  * <list>             <chr>  <list>           <list>
# >  1 <split [1.4K/152]> Fold01 <tibble [2 × 3]> <tibble [0 × 1]>
# >  2 <split [1.4K/152]> Fold02 <tibble [2 × 3]> <tibble [0 × 1]>
# >  3 <split [1.4K/152]> Fold03 <tibble [2 × 3]> <tibble [0 × 1]>
# >  4 <split [1.4K/152]> Fold04 <tibble [2 × 3]> <tibble [0 × 1]>
# >  5 <split [1.4K/152]> Fold05 <tibble [2 × 3]> <tibble [0 × 1]>
# >  6 <split [1.4K/151]> Fold06 <tibble [2 × 3]> <tibble [0 × 1]>
# >  7 <split [1.4K/151]> Fold07 <tibble [2 × 3]> <tibble [0 × 1]>
# >  8 <split [1.4K/151]> Fold08 <tibble [2 × 3]> <tibble [0 × 1]>
# >  9 <split [1.4K/151]> Fold09 <tibble [2 × 3]> <tibble [0 × 1]>
# > 10 <split [1.4K/151]> Fold10 <tibble [2 × 3]> <tibble [0 × 1]>

```

```{r}
collect_metrics(rf_fit_rs)
# > # A tibble: 2 x 5
# >   .metric  .estimator  mean     n std_err
# >   <chr>    <chr>      <dbl> <int>   <dbl>
# > 1 accuracy binary     0.833    10 0.0111
# > 2 roc_auc  binary     0.903    10 0.00842

```

```{r}
rf_testing_pred %>%                   # test set predictions
  roc_auc(truth = class, .pred_A, .pred_B, .pred_C, .pred_D, .pred_E)
  # > # A tibble: 1 x 3
  # >   .metric .estimator .estimate
  # >   <chr>   <chr>          <dbl>
  # > 1 roc_auc binary         0.909
  rf_testing_pred %>% # test set predictions
      accuracy(truth = class, .pred_class)
  # > # A tibble: 1 x 3
  # >   .metric  .estimator .estimate
  # >   <chr>    <chr>          <dbl>
# > 1 accuracy binary         0.837

```
